// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tobnirfbqpyjxapsjrfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvYm5pcmZicXB5anhhcHNqcmZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwODQwNzYsImV4cCI6MjA2MzY2MDA3Nn0.kCEXXiCAUb7nuZyWPvxSxIq5yEY-iyy2PW-XBzbbGug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);